Repository redBorder/redborder-cookbooks, pull requests merged in 2023-11, with the labels that each got.

#20 Rhel9
  packaging/rpm/redborder-cookbooks.spec
Labels: kind/bug, size/XS

#21 Add cookbook rb-cgroup as dependency
  packaging/rpm/redborder-cookbooks.spec
Labels: size/XS, kind/feature

#23 Release 1.0.4
  packaging/rpm/redborder-cookbooks.spec
Labels: size/XS, kind/documentation
